steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/second-project-mlops/demo-flask-app:$_COMMIT_SHA'
    - '.'

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'gcr.io/second-project-mlops/demo-flask-app:$_COMMIT_SHA'

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - 'echo "Pulling image: gcr.io/second-project-mlops/demo-flask-app:$_COMMIT_SHA"'

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'pull'
    - 'gcr.io/second-project-mlops/demo-flask-app:$_COMMIT_SHA'

- name: 'python:3.9'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Installing dependencies..."
      pip install --no-cache-dir -r requirements.txt || exit 1
      echo "Running tests..."
      python -m pytest || exit 1

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'py-bq-load'
    - '--image'
    - 'gcr.io/second-project-mlops/demo-flask-app:$_COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--allow-unauthenticated'

images:
  - 'gcr.io/second-project-mlops/demo-flask-app:$_COMMIT_SHA'

substitutions:
  _COMMIT_SHA: "latest"

options:
  logging: CLOUD_LOGGING_ONLY
